version: '3.8'

services:

  books:
    image: books-micro
    container_name: books
    networks:
      - library-soa
    ports:
      - "8085:5000"

  loans:
    image: loans-micro
    container_name: loans
    networks:
      - library-soa
    ports:
      - "8086:5000"

  users:
    image: users-micro
    container_name: users
    ports:
      - "8087:5000"
    networks:
      - library-soa